apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-chat-1-ci
  namespace: rhtap-gitops
  finalizers: ["resources-finalizer.argocd.argoproj.io"]
spec:
  project: default
  source:
    path: ./components/test-chat-1/overlays/ci
    repoURL: https://github.com/rhtap-test-organization-jk/test-chat-1-gitops.git
    targetRevision: main
  destination:
    namespace: tssc-app-ci
    server: https://kubernetes.default.svc
  syncPolicy:
    managedNamespaceMetadata:
      labels:
        argocd.argoproj.io/managed-by: rhtap-gitops
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
