apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: test-chat-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-chat-1 
  name: test-chat-1
spec:
  ports:
  - port: 8080 
    targetPort: 8080 
  selector:
    app.kubernetes.io/instance: test-chat-1 
